using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace AmazonFarmer.Core.Application.DTOs
{
    public class AuthorityLetterList
    {
        public int AuthorityLetterID { get; set; }
        public string AuthorityLetterNo { get; set; }
        public string LetterDate { get; set; }
        public string Product { get; set;}
        public string Dealer { get; set;}
        public int Quantity { get; set;}
        public string Bearer { get; set;}
        public string BearerNic { get; set;}
        public bool AutoGenerated { get; set;}
        public string InvoiceNo { get; set;}
        public string Status { get; set;}
    }
}
