//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChangeCustomerPayment
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:sap-com:document:sap:rfc:functions", ConfigurationName="ChangeCustomerPayment.ZSD_AMZ_CUSTOMER_PAY_CHG_SRV")]
    public interface ZSD_AMZ_CUSTOMER_PAY_CHG_SRV
    {
        
        // CODEGEN: Generating message contract since the operation ZSD_AMAZON_CUSTOMER_PAY_CHG is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="urn:sap-com:document:sap:rfc:functions:ZSD_AMZ_CUSTOMER_PAY_CHG_SRV:ZSD_AMAZON_CU" +
            "STOMER_PAY_CHGRequest", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ChangeCustomerPayment.ZSD_AMAZON_CUSTOMER_PAY_CHGResponse1 ZSD_AMAZON_CUSTOMER_PAY_CHG(ChangeCustomerPayment.ZSD_AMAZON_CUSTOMER_PAY_CHGRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:sap-com:document:sap:rfc:functions:ZSD_AMZ_CUSTOMER_PAY_CHG_SRV:ZSD_AMAZON_CU" +
            "STOMER_PAY_CHGRequest", ReplyAction="*")]
        System.Threading.Tasks.Task<ChangeCustomerPayment.ZSD_AMAZON_CUSTOMER_PAY_CHGResponse1> ZSD_AMAZON_CUSTOMER_PAY_CHGAsync(ChangeCustomerPayment.ZSD_AMAZON_CUSTOMER_PAY_CHGRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class ZSD_AMAZON_CUSTOMER_PAY_CHG
    {
        
        private string cOMPANY_CODEField;
        
        private string dOC_NUMField;
        
        private string fISCAL_YEARField;
        
        private string rEASON_CODEField;
        
        private string tEXTField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string COMPANY_CODE
        {
            get
            {
                return this.cOMPANY_CODEField;
            }
            set
            {
                this.cOMPANY_CODEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string DOC_NUM
        {
            get
            {
                return this.dOC_NUMField;
            }
            set
            {
                this.dOC_NUMField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string FISCAL_YEAR
        {
            get
            {
                return this.fISCAL_YEARField;
            }
            set
            {
                this.fISCAL_YEARField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string REASON_CODE
        {
            get
            {
                return this.rEASON_CODEField;
            }
            set
            {
                this.rEASON_CODEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string TEXT
        {
            get
            {
                return this.tEXTField;
            }
            set
            {
                this.tEXTField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class ZSTR_AMAZON_RESPONSE
    {
        
        private string mSGField;
        
        private string mSGNRField;
        
        private string mSGTYPField;
        
        private string cATEGORYField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string MSG
        {
            get
            {
                return this.mSGField;
            }
            set
            {
                this.mSGField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string MSGNR
        {
            get
            {
                return this.mSGNRField;
            }
            set
            {
                this.mSGNRField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string MSGTYP
        {
            get
            {
                return this.mSGTYPField;
            }
            set
            {
                this.mSGTYPField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string CATEGORY
        {
            get
            {
                return this.cATEGORYField;
            }
            set
            {
                this.cATEGORYField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class ZSD_AMAZON_CUSTOMER_PAY_CHGResponse
    {
        
        private ZSTR_AMAZON_RESPONSE[] eT_RETURNField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public ZSTR_AMAZON_RESPONSE[] ET_RETURN
        {
            get
            {
                return this.eT_RETURNField;
            }
            set
            {
                this.eT_RETURNField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ZSD_AMAZON_CUSTOMER_PAY_CHGRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:rfc:functions", Order=0)]
        public ChangeCustomerPayment.ZSD_AMAZON_CUSTOMER_PAY_CHG ZSD_AMAZON_CUSTOMER_PAY_CHG;
        
        public ZSD_AMAZON_CUSTOMER_PAY_CHGRequest()
        {
        }
        
        public ZSD_AMAZON_CUSTOMER_PAY_CHGRequest(ChangeCustomerPayment.ZSD_AMAZON_CUSTOMER_PAY_CHG ZSD_AMAZON_CUSTOMER_PAY_CHG)
        {
            this.ZSD_AMAZON_CUSTOMER_PAY_CHG = ZSD_AMAZON_CUSTOMER_PAY_CHG;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ZSD_AMAZON_CUSTOMER_PAY_CHGResponse1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ZSD_AMAZON_CUSTOMER_PAY_CHG.Response", Namespace="urn:sap-com:document:sap:rfc:functions", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("ZSD_AMAZON_CUSTOMER_PAY_CHG.Response")]
        public ChangeCustomerPayment.ZSD_AMAZON_CUSTOMER_PAY_CHGResponse ZSD_AMAZON_CUSTOMER_PAY_CHGResponse;
        
        public ZSD_AMAZON_CUSTOMER_PAY_CHGResponse1()
        {
        }
        
        public ZSD_AMAZON_CUSTOMER_PAY_CHGResponse1(ChangeCustomerPayment.ZSD_AMAZON_CUSTOMER_PAY_CHGResponse ZSD_AMAZON_CUSTOMER_PAY_CHGResponse)
        {
            this.ZSD_AMAZON_CUSTOMER_PAY_CHGResponse = ZSD_AMAZON_CUSTOMER_PAY_CHGResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public interface ZSD_AMZ_CUSTOMER_PAY_CHG_SRVChannel : ChangeCustomerPayment.ZSD_AMZ_CUSTOMER_PAY_CHG_SRV, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public partial class ZSD_AMZ_CUSTOMER_PAY_CHG_SRVClient : System.ServiceModel.ClientBase<ChangeCustomerPayment.ZSD_AMZ_CUSTOMER_PAY_CHG_SRV>, ChangeCustomerPayment.ZSD_AMZ_CUSTOMER_PAY_CHG_SRV
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public ZSD_AMZ_CUSTOMER_PAY_CHG_SRVClient() : 
                base(ZSD_AMZ_CUSTOMER_PAY_CHG_SRVClient.GetDefaultBinding(), ZSD_AMZ_CUSTOMER_PAY_CHG_SRVClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.binding.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ZSD_AMZ_CUSTOMER_PAY_CHG_SRVClient(EndpointConfiguration endpointConfiguration) : 
                base(ZSD_AMZ_CUSTOMER_PAY_CHG_SRVClient.GetBindingForEndpoint(endpointConfiguration), ZSD_AMZ_CUSTOMER_PAY_CHG_SRVClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ZSD_AMZ_CUSTOMER_PAY_CHG_SRVClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(ZSD_AMZ_CUSTOMER_PAY_CHG_SRVClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ZSD_AMZ_CUSTOMER_PAY_CHG_SRVClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(ZSD_AMZ_CUSTOMER_PAY_CHG_SRVClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ZSD_AMZ_CUSTOMER_PAY_CHG_SRVClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ChangeCustomerPayment.ZSD_AMAZON_CUSTOMER_PAY_CHGResponse1 ChangeCustomerPayment.ZSD_AMZ_CUSTOMER_PAY_CHG_SRV.ZSD_AMAZON_CUSTOMER_PAY_CHG(ChangeCustomerPayment.ZSD_AMAZON_CUSTOMER_PAY_CHGRequest request)
        {
            return base.Channel.ZSD_AMAZON_CUSTOMER_PAY_CHG(request);
        }
        
        public ChangeCustomerPayment.ZSD_AMAZON_CUSTOMER_PAY_CHGResponse ZSD_AMAZON_CUSTOMER_PAY_CHG(ChangeCustomerPayment.ZSD_AMAZON_CUSTOMER_PAY_CHG ZSD_AMAZON_CUSTOMER_PAY_CHG1)
        {
            ChangeCustomerPayment.ZSD_AMAZON_CUSTOMER_PAY_CHGRequest inValue = new ChangeCustomerPayment.ZSD_AMAZON_CUSTOMER_PAY_CHGRequest();
            inValue.ZSD_AMAZON_CUSTOMER_PAY_CHG = ZSD_AMAZON_CUSTOMER_PAY_CHG1;
            ChangeCustomerPayment.ZSD_AMAZON_CUSTOMER_PAY_CHGResponse1 retVal = ((ChangeCustomerPayment.ZSD_AMZ_CUSTOMER_PAY_CHG_SRV)(this)).ZSD_AMAZON_CUSTOMER_PAY_CHG(inValue);
            return retVal.ZSD_AMAZON_CUSTOMER_PAY_CHGResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ChangeCustomerPayment.ZSD_AMAZON_CUSTOMER_PAY_CHGResponse1> ChangeCustomerPayment.ZSD_AMZ_CUSTOMER_PAY_CHG_SRV.ZSD_AMAZON_CUSTOMER_PAY_CHGAsync(ChangeCustomerPayment.ZSD_AMAZON_CUSTOMER_PAY_CHGRequest request)
        {
            return base.Channel.ZSD_AMAZON_CUSTOMER_PAY_CHGAsync(request);
        }
        
        public System.Threading.Tasks.Task<ChangeCustomerPayment.ZSD_AMAZON_CUSTOMER_PAY_CHGResponse1> ZSD_AMAZON_CUSTOMER_PAY_CHGAsync(ChangeCustomerPayment.ZSD_AMAZON_CUSTOMER_PAY_CHG ZSD_AMAZON_CUSTOMER_PAY_CHG)
        {
            ChangeCustomerPayment.ZSD_AMAZON_CUSTOMER_PAY_CHGRequest inValue = new ChangeCustomerPayment.ZSD_AMAZON_CUSTOMER_PAY_CHGRequest();
            inValue.ZSD_AMAZON_CUSTOMER_PAY_CHG = ZSD_AMAZON_CUSTOMER_PAY_CHG;
            return ((ChangeCustomerPayment.ZSD_AMZ_CUSTOMER_PAY_CHG_SRV)(this)).ZSD_AMAZON_CUSTOMER_PAY_CHGAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.binding))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.binding))
            {
                return new System.ServiceModel.EndpointAddress("https://onesapbtpqa.it-cpi016-rt.cfapps.ap20.hana.ondemand.com/cxf/Amazon/Customer" +
                        "PaymentChg");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return ZSD_AMZ_CUSTOMER_PAY_CHG_SRVClient.GetBindingForEndpoint(EndpointConfiguration.binding);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return ZSD_AMZ_CUSTOMER_PAY_CHG_SRVClient.GetEndpointAddress(EndpointConfiguration.binding);
        }
        
        public enum EndpointConfiguration
        {
            
            binding,
        }
    }
}
