//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChangeSaleOrder
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:sap-com:document:sap:rfc:functions", ConfigurationName="ChangeSaleOrder.zsd_amazon_saleord_chg_srv")]
    public interface zsd_amazon_saleord_chg_srv
    {
        
        // CODEGEN: Generating message contract since the operation ZSD_AMAZON_SALEORD_CHG is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="urn:sap-com:document:sap:rfc:functions:zsd_amazon_saleord_chg_srv:ZSD_AMAZON_SALE" +
            "ORD_CHGRequest", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ChangeSaleOrder.ZSD_AMAZON_SALEORD_CHGResponse1 ZSD_AMAZON_SALEORD_CHG(ChangeSaleOrder.ZSD_AMAZON_SALEORD_CHGRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:sap-com:document:sap:rfc:functions:zsd_amazon_saleord_chg_srv:ZSD_AMAZON_SALE" +
            "ORD_CHGRequest", ReplyAction="*")]
        System.Threading.Tasks.Task<ChangeSaleOrder.ZSD_AMAZON_SALEORD_CHGResponse1> ZSD_AMAZON_SALEORD_CHGAsync(ChangeSaleOrder.ZSD_AMAZON_SALEORD_CHGRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class ZSD_AMAZON_SALEORD_CHG
    {
        
        private string cONDGRP_1Field;
        
        private string cONDGRP_2Field;
        
        private string cONDGRP_3Field;
        
        private string cONDGRP_4Field;
        
        private string cUST_REFField;
        
        private string pLANTField;
        
        private string rEASON_REJField;
        
        private string rEQ_DELIVERY_DATEField;
        
        private string sALE_ORDField;
        
        private string sTORAGE_LOCField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string CONDGRP_1
        {
            get
            {
                return this.cONDGRP_1Field;
            }
            set
            {
                this.cONDGRP_1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string CONDGRP_2
        {
            get
            {
                return this.cONDGRP_2Field;
            }
            set
            {
                this.cONDGRP_2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string CONDGRP_3
        {
            get
            {
                return this.cONDGRP_3Field;
            }
            set
            {
                this.cONDGRP_3Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string CONDGRP_4
        {
            get
            {
                return this.cONDGRP_4Field;
            }
            set
            {
                this.cONDGRP_4Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string CUST_REF
        {
            get
            {
                return this.cUST_REFField;
            }
            set
            {
                this.cUST_REFField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string PLANT
        {
            get
            {
                return this.pLANTField;
            }
            set
            {
                this.pLANTField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string REASON_REJ
        {
            get
            {
                return this.rEASON_REJField;
            }
            set
            {
                this.rEASON_REJField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string REQ_DELIVERY_DATE
        {
            get
            {
                return this.rEQ_DELIVERY_DATEField;
            }
            set
            {
                this.rEQ_DELIVERY_DATEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string SALE_ORD
        {
            get
            {
                return this.sALE_ORDField;
            }
            set
            {
                this.sALE_ORDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string STORAGE_LOC
        {
            get
            {
                return this.sTORAGE_LOCField;
            }
            set
            {
                this.sTORAGE_LOCField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class ZSTR_AMAZON_RESPONSE
    {
        
        private string mSGField;
        
        private string mSGNRField;
        
        private string mSGTYPField;
        
        private string cATEGORYField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string MSG
        {
            get
            {
                return this.mSGField;
            }
            set
            {
                this.mSGField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string MSGNR
        {
            get
            {
                return this.mSGNRField;
            }
            set
            {
                this.mSGNRField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string MSGTYP
        {
            get
            {
                return this.mSGTYPField;
            }
            set
            {
                this.mSGTYPField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string CATEGORY
        {
            get
            {
                return this.cATEGORYField;
            }
            set
            {
                this.cATEGORYField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class ZSD_AMAZON_SALEORD_CHGResponse
    {
        
        private ZSTR_AMAZON_RESPONSE[] eT_RETURNField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public ZSTR_AMAZON_RESPONSE[] ET_RETURN
        {
            get
            {
                return this.eT_RETURNField;
            }
            set
            {
                this.eT_RETURNField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ZSD_AMAZON_SALEORD_CHGRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:rfc:functions", Order=0)]
        public ChangeSaleOrder.ZSD_AMAZON_SALEORD_CHG ZSD_AMAZON_SALEORD_CHG;
        
        public ZSD_AMAZON_SALEORD_CHGRequest()
        {
        }
        
        public ZSD_AMAZON_SALEORD_CHGRequest(ChangeSaleOrder.ZSD_AMAZON_SALEORD_CHG ZSD_AMAZON_SALEORD_CHG)
        {
            this.ZSD_AMAZON_SALEORD_CHG = ZSD_AMAZON_SALEORD_CHG;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ZSD_AMAZON_SALEORD_CHGResponse1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ZSD_AMAZON_SALEORD_CHG.Response", Namespace="urn:sap-com:document:sap:rfc:functions", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("ZSD_AMAZON_SALEORD_CHG.Response")]
        public ChangeSaleOrder.ZSD_AMAZON_SALEORD_CHGResponse ZSD_AMAZON_SALEORD_CHGResponse;
        
        public ZSD_AMAZON_SALEORD_CHGResponse1()
        {
        }
        
        public ZSD_AMAZON_SALEORD_CHGResponse1(ChangeSaleOrder.ZSD_AMAZON_SALEORD_CHGResponse ZSD_AMAZON_SALEORD_CHGResponse)
        {
            this.ZSD_AMAZON_SALEORD_CHGResponse = ZSD_AMAZON_SALEORD_CHGResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public interface zsd_amazon_saleord_chg_srvChannel : ChangeSaleOrder.zsd_amazon_saleord_chg_srv, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public partial class zsd_amazon_saleord_chg_srvClient : System.ServiceModel.ClientBase<ChangeSaleOrder.zsd_amazon_saleord_chg_srv>, ChangeSaleOrder.zsd_amazon_saleord_chg_srv
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public zsd_amazon_saleord_chg_srvClient() : 
                base(zsd_amazon_saleord_chg_srvClient.GetDefaultBinding(), zsd_amazon_saleord_chg_srvClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.binding.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public zsd_amazon_saleord_chg_srvClient(EndpointConfiguration endpointConfiguration) : 
                base(zsd_amazon_saleord_chg_srvClient.GetBindingForEndpoint(endpointConfiguration), zsd_amazon_saleord_chg_srvClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public zsd_amazon_saleord_chg_srvClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(zsd_amazon_saleord_chg_srvClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public zsd_amazon_saleord_chg_srvClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(zsd_amazon_saleord_chg_srvClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public zsd_amazon_saleord_chg_srvClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ChangeSaleOrder.ZSD_AMAZON_SALEORD_CHGResponse1 ChangeSaleOrder.zsd_amazon_saleord_chg_srv.ZSD_AMAZON_SALEORD_CHG(ChangeSaleOrder.ZSD_AMAZON_SALEORD_CHGRequest request)
        {
            return base.Channel.ZSD_AMAZON_SALEORD_CHG(request);
        }
        
        public ChangeSaleOrder.ZSD_AMAZON_SALEORD_CHGResponse ZSD_AMAZON_SALEORD_CHG(ChangeSaleOrder.ZSD_AMAZON_SALEORD_CHG ZSD_AMAZON_SALEORD_CHG1)
        {
            ChangeSaleOrder.ZSD_AMAZON_SALEORD_CHGRequest inValue = new ChangeSaleOrder.ZSD_AMAZON_SALEORD_CHGRequest();
            inValue.ZSD_AMAZON_SALEORD_CHG = ZSD_AMAZON_SALEORD_CHG1;
            ChangeSaleOrder.ZSD_AMAZON_SALEORD_CHGResponse1 retVal = ((ChangeSaleOrder.zsd_amazon_saleord_chg_srv)(this)).ZSD_AMAZON_SALEORD_CHG(inValue);
            return retVal.ZSD_AMAZON_SALEORD_CHGResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ChangeSaleOrder.ZSD_AMAZON_SALEORD_CHGResponse1> ChangeSaleOrder.zsd_amazon_saleord_chg_srv.ZSD_AMAZON_SALEORD_CHGAsync(ChangeSaleOrder.ZSD_AMAZON_SALEORD_CHGRequest request)
        {
            return base.Channel.ZSD_AMAZON_SALEORD_CHGAsync(request);
        }
        
        public System.Threading.Tasks.Task<ChangeSaleOrder.ZSD_AMAZON_SALEORD_CHGResponse1> ZSD_AMAZON_SALEORD_CHGAsync(ChangeSaleOrder.ZSD_AMAZON_SALEORD_CHG ZSD_AMAZON_SALEORD_CHG)
        {
            ChangeSaleOrder.ZSD_AMAZON_SALEORD_CHGRequest inValue = new ChangeSaleOrder.ZSD_AMAZON_SALEORD_CHGRequest();
            inValue.ZSD_AMAZON_SALEORD_CHG = ZSD_AMAZON_SALEORD_CHG;
            return ((ChangeSaleOrder.zsd_amazon_saleord_chg_srv)(this)).ZSD_AMAZON_SALEORD_CHGAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.binding))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.binding))
            {
                return new System.ServiceModel.EndpointAddress("https://onesapbtpqa.it-cpi016-rt.cfapps.ap20.hana.ondemand.com/cxf/Amazon/SaleOrdC" +
                        "hange");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return zsd_amazon_saleord_chg_srvClient.GetBindingForEndpoint(EndpointConfiguration.binding);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return zsd_amazon_saleord_chg_srvClient.GetEndpointAddress(EndpointConfiguration.binding);
        }
        
        public enum EndpointConfiguration
        {
            
            binding,
        }
    }
}
