//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PaymentCustomer
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:sap-com:document:sap:rfc:functions", ConfigurationName="PaymentCustomer.ZSD_AMA_CUSTOMER_PAYMENT_SRV")]
    public interface ZSD_AMA_CUSTOMER_PAYMENT_SRV
    {
        
        // CODEGEN: Generating message contract since the operation ZSD_AMAZON_CUSTOMER_PAYMENT is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="urn:sap-com:document:sap:rfc:functions:ZSD_AMA_CUSTOMER_PAYMENT_SRV:ZSD_AMAZON_CU" +
            "STOMER_PAYMENTRequest", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        PaymentCustomer.ZSD_AMAZON_CUSTOMER_PAYMENTResponse1 ZSD_AMAZON_CUSTOMER_PAYMENT(PaymentCustomer.ZSD_AMAZON_CUSTOMER_PAYMENTRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:sap-com:document:sap:rfc:functions:ZSD_AMA_CUSTOMER_PAYMENT_SRV:ZSD_AMAZON_CU" +
            "STOMER_PAYMENTRequest", ReplyAction="*")]
        System.Threading.Tasks.Task<PaymentCustomer.ZSD_AMAZON_CUSTOMER_PAYMENTResponse1> ZSD_AMAZON_CUSTOMER_PAYMENTAsync(PaymentCustomer.ZSD_AMAZON_CUSTOMER_PAYMENTRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class ZSD_AMAZON_CUSTOMER_PAYMENT
    {
        
        private decimal aMOUNTField;
        
        private bool aMOUNTFieldSpecified;
        
        private string bASELINE_DATEField;
        
        private string cOMPANY_CODEField;
        
        private string cUST_ACCField;
        
        private string dOC_DATEField;
        
        private string dOC_HEADERField;
        
        private string pOSTING_DATEField;
        
        private string rEASON_CODEField;
        
        private string rEFField;
        
        private string tEXTField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public decimal AMOUNT
        {
            get
            {
                return this.aMOUNTField;
            }
            set
            {
                this.aMOUNTField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool AMOUNTSpecified
        {
            get
            {
                return this.aMOUNTFieldSpecified;
            }
            set
            {
                this.aMOUNTFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string BASELINE_DATE
        {
            get
            {
                return this.bASELINE_DATEField;
            }
            set
            {
                this.bASELINE_DATEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string COMPANY_CODE
        {
            get
            {
                return this.cOMPANY_CODEField;
            }
            set
            {
                this.cOMPANY_CODEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string CUST_ACC
        {
            get
            {
                return this.cUST_ACCField;
            }
            set
            {
                this.cUST_ACCField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string DOC_DATE
        {
            get
            {
                return this.dOC_DATEField;
            }
            set
            {
                this.dOC_DATEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string DOC_HEADER
        {
            get
            {
                return this.dOC_HEADERField;
            }
            set
            {
                this.dOC_HEADERField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string POSTING_DATE
        {
            get
            {
                return this.pOSTING_DATEField;
            }
            set
            {
                this.pOSTING_DATEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string REASON_CODE
        {
            get
            {
                return this.rEASON_CODEField;
            }
            set
            {
                this.rEASON_CODEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string REF
        {
            get
            {
                return this.rEFField;
            }
            set
            {
                this.rEFField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string TEXT
        {
            get
            {
                return this.tEXTField;
            }
            set
            {
                this.tEXTField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class ZSTR_AMAZON_RESPONSE
    {
        
        private string mSGField;
        
        private string mSGNRField;
        
        private string mSGTYPField;
        
        private string cATEGORYField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string MSG
        {
            get
            {
                return this.mSGField;
            }
            set
            {
                this.mSGField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string MSGNR
        {
            get
            {
                return this.mSGNRField;
            }
            set
            {
                this.mSGNRField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string MSGTYP
        {
            get
            {
                return this.mSGTYPField;
            }
            set
            {
                this.mSGTYPField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string CATEGORY
        {
            get
            {
                return this.cATEGORYField;
            }
            set
            {
                this.cATEGORYField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class ZSD_AMAZON_CUSTOMER_PAYMENTResponse
    {
        
        private string dOC_NUMField;
        
        private string eCOMPANY_CODEField;
        
        private ZSTR_AMAZON_RESPONSE[] eT_RETURNField;
        
        private string fISCAL_YEARField;
        
        private string oBJECT_KEYField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string DOC_NUM
        {
            get
            {
                return this.dOC_NUMField;
            }
            set
            {
                this.dOC_NUMField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string ECOMPANY_CODE
        {
            get
            {
                return this.eCOMPANY_CODEField;
            }
            set
            {
                this.eCOMPANY_CODEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public ZSTR_AMAZON_RESPONSE[] ET_RETURN
        {
            get
            {
                return this.eT_RETURNField;
            }
            set
            {
                this.eT_RETURNField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string FISCAL_YEAR
        {
            get
            {
                return this.fISCAL_YEARField;
            }
            set
            {
                this.fISCAL_YEARField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string OBJECT_KEY
        {
            get
            {
                return this.oBJECT_KEYField;
            }
            set
            {
                this.oBJECT_KEYField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ZSD_AMAZON_CUSTOMER_PAYMENTRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:rfc:functions", Order=0)]
        public PaymentCustomer.ZSD_AMAZON_CUSTOMER_PAYMENT ZSD_AMAZON_CUSTOMER_PAYMENT;
        
        public ZSD_AMAZON_CUSTOMER_PAYMENTRequest()
        {
        }
        
        public ZSD_AMAZON_CUSTOMER_PAYMENTRequest(PaymentCustomer.ZSD_AMAZON_CUSTOMER_PAYMENT ZSD_AMAZON_CUSTOMER_PAYMENT)
        {
            this.ZSD_AMAZON_CUSTOMER_PAYMENT = ZSD_AMAZON_CUSTOMER_PAYMENT;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ZSD_AMAZON_CUSTOMER_PAYMENTResponse1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ZSD_AMAZON_CUSTOMER_PAYMENT.Response", Namespace="urn:sap-com:document:sap:rfc:functions", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("ZSD_AMAZON_CUSTOMER_PAYMENT.Response")]
        public PaymentCustomer.ZSD_AMAZON_CUSTOMER_PAYMENTResponse ZSD_AMAZON_CUSTOMER_PAYMENTResponse;
        
        public ZSD_AMAZON_CUSTOMER_PAYMENTResponse1()
        {
        }
        
        public ZSD_AMAZON_CUSTOMER_PAYMENTResponse1(PaymentCustomer.ZSD_AMAZON_CUSTOMER_PAYMENTResponse ZSD_AMAZON_CUSTOMER_PAYMENTResponse)
        {
            this.ZSD_AMAZON_CUSTOMER_PAYMENTResponse = ZSD_AMAZON_CUSTOMER_PAYMENTResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public interface ZSD_AMA_CUSTOMER_PAYMENT_SRVChannel : PaymentCustomer.ZSD_AMA_CUSTOMER_PAYMENT_SRV, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public partial class ZSD_AMA_CUSTOMER_PAYMENT_SRVClient : System.ServiceModel.ClientBase<PaymentCustomer.ZSD_AMA_CUSTOMER_PAYMENT_SRV>, PaymentCustomer.ZSD_AMA_CUSTOMER_PAYMENT_SRV
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public ZSD_AMA_CUSTOMER_PAYMENT_SRVClient() : 
                base(ZSD_AMA_CUSTOMER_PAYMENT_SRVClient.GetDefaultBinding(), ZSD_AMA_CUSTOMER_PAYMENT_SRVClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.binding.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ZSD_AMA_CUSTOMER_PAYMENT_SRVClient(EndpointConfiguration endpointConfiguration) : 
                base(ZSD_AMA_CUSTOMER_PAYMENT_SRVClient.GetBindingForEndpoint(endpointConfiguration), ZSD_AMA_CUSTOMER_PAYMENT_SRVClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ZSD_AMA_CUSTOMER_PAYMENT_SRVClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(ZSD_AMA_CUSTOMER_PAYMENT_SRVClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ZSD_AMA_CUSTOMER_PAYMENT_SRVClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(ZSD_AMA_CUSTOMER_PAYMENT_SRVClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ZSD_AMA_CUSTOMER_PAYMENT_SRVClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PaymentCustomer.ZSD_AMAZON_CUSTOMER_PAYMENTResponse1 PaymentCustomer.ZSD_AMA_CUSTOMER_PAYMENT_SRV.ZSD_AMAZON_CUSTOMER_PAYMENT(PaymentCustomer.ZSD_AMAZON_CUSTOMER_PAYMENTRequest request)
        {
            return base.Channel.ZSD_AMAZON_CUSTOMER_PAYMENT(request);
        }
        
        public PaymentCustomer.ZSD_AMAZON_CUSTOMER_PAYMENTResponse ZSD_AMAZON_CUSTOMER_PAYMENT(PaymentCustomer.ZSD_AMAZON_CUSTOMER_PAYMENT ZSD_AMAZON_CUSTOMER_PAYMENT1)
        {
            PaymentCustomer.ZSD_AMAZON_CUSTOMER_PAYMENTRequest inValue = new PaymentCustomer.ZSD_AMAZON_CUSTOMER_PAYMENTRequest();
            inValue.ZSD_AMAZON_CUSTOMER_PAYMENT = ZSD_AMAZON_CUSTOMER_PAYMENT1;
            PaymentCustomer.ZSD_AMAZON_CUSTOMER_PAYMENTResponse1 retVal = ((PaymentCustomer.ZSD_AMA_CUSTOMER_PAYMENT_SRV)(this)).ZSD_AMAZON_CUSTOMER_PAYMENT(inValue);
            return retVal.ZSD_AMAZON_CUSTOMER_PAYMENTResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PaymentCustomer.ZSD_AMAZON_CUSTOMER_PAYMENTResponse1> PaymentCustomer.ZSD_AMA_CUSTOMER_PAYMENT_SRV.ZSD_AMAZON_CUSTOMER_PAYMENTAsync(PaymentCustomer.ZSD_AMAZON_CUSTOMER_PAYMENTRequest request)
        {
            return base.Channel.ZSD_AMAZON_CUSTOMER_PAYMENTAsync(request);
        }
        
        public System.Threading.Tasks.Task<PaymentCustomer.ZSD_AMAZON_CUSTOMER_PAYMENTResponse1> ZSD_AMAZON_CUSTOMER_PAYMENTAsync(PaymentCustomer.ZSD_AMAZON_CUSTOMER_PAYMENT ZSD_AMAZON_CUSTOMER_PAYMENT)
        {
            PaymentCustomer.ZSD_AMAZON_CUSTOMER_PAYMENTRequest inValue = new PaymentCustomer.ZSD_AMAZON_CUSTOMER_PAYMENTRequest();
            inValue.ZSD_AMAZON_CUSTOMER_PAYMENT = ZSD_AMAZON_CUSTOMER_PAYMENT;
            return ((PaymentCustomer.ZSD_AMA_CUSTOMER_PAYMENT_SRV)(this)).ZSD_AMAZON_CUSTOMER_PAYMENTAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.binding))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.binding))
            {
                return new System.ServiceModel.EndpointAddress("https://onesapbtpqa.it-cpi016-rt.cfapps.ap20.hana.ondemand.com/cxf/Amazon/Customer" +
                        "Payment");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return ZSD_AMA_CUSTOMER_PAYMENT_SRVClient.GetBindingForEndpoint(EndpointConfiguration.binding);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return ZSD_AMA_CUSTOMER_PAYMENT_SRVClient.GetEndpointAddress(EndpointConfiguration.binding);
        }
        
        public enum EndpointConfiguration
        {
            
            binding,
        }
    }
}
