//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DetailsInvoice
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:sap-com:document:sap:rfc:functions", ConfigurationName="DetailsInvoice.ZSD_AMAZ_ORDER_INV_DETAILS_SRV")]
    public interface ZSD_AMAZ_ORDER_INV_DETAILS_SRV
    {
        
        // CODEGEN: Generating message contract since the operation ZSD_AMAZ_ORDER_INV_DETAILS is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="urn:sap-com:document:sap:rfc:functions:ZSD_AMAZ_ORDER_INV_DETAILS_SRV:ZSD_AMAZ_OR" +
            "DER_INV_DETAILSRequest", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        DetailsInvoice.ZSD_AMAZ_ORDER_INV_DETAILSResponse1 ZSD_AMAZ_ORDER_INV_DETAILS(DetailsInvoice.ZSD_AMAZ_ORDER_INV_DETAILSRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:sap-com:document:sap:rfc:functions:ZSD_AMAZ_ORDER_INV_DETAILS_SRV:ZSD_AMAZ_OR" +
            "DER_INV_DETAILSRequest", ReplyAction="*")]
        System.Threading.Tasks.Task<DetailsInvoice.ZSD_AMAZ_ORDER_INV_DETAILSResponse1> ZSD_AMAZ_ORDER_INV_DETAILSAsync(DetailsInvoice.ZSD_AMAZ_ORDER_INV_DETAILSRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class ZSD_AMAZ_ORDER_INV_DETAILS
    {
        
        private string i_AUBELField;
        
        private string i_VBELNField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string I_AUBEL
        {
            get
            {
                return this.i_AUBELField;
            }
            set
            {
                this.i_AUBELField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string I_VBELN
        {
            get
            {
                return this.i_VBELNField;
            }
            set
            {
                this.i_VBELNField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class ZSD_AMAZ_ORDER_INV
    {
        
        private string vBELNField;
        
        private string pOSNRField;
        
        private string kUNAGField;
        
        private string nAME1Field;
        
        private string vKBURField;
        
        private string aRKTXField;
        
        private string vKGRPField;
        
        private string bEZEIField;
        
        private string bZIRKField;
        
        private string bZTXTField;
        
        private string fKDATField;
        
        private string aUBELField;
        
        private string aUPOSField;
        
        private string vGBELField;
        
        private string vGPOSField;
        
        private string mATNRField;
        
        private string mAKTXField;
        
        private decimal fKIMGField;
        
        private string vRKMEField;
        
        private string mATKLField;
        
        private string lGORTField;
        
        private string lGOBEField;
        
        private string wERKSField;
        
        private string wERKS_DField;
        
        private decimal cMPREField;
        
        private decimal nETWRField;
        
        private decimal mWSBPField;
        
        private decimal kZWI6Field;
        
        private decimal kZWI5Field;
        
        private decimal xWORKGField;
        
        private decimal xWORKFField;
        
        private decimal xWORKEField;
        
        private string kMEINField;
        
        private string wAERSField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string VBELN
        {
            get
            {
                return this.vBELNField;
            }
            set
            {
                this.vBELNField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string POSNR
        {
            get
            {
                return this.pOSNRField;
            }
            set
            {
                this.pOSNRField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string KUNAG
        {
            get
            {
                return this.kUNAGField;
            }
            set
            {
                this.kUNAGField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string NAME1
        {
            get
            {
                return this.nAME1Field;
            }
            set
            {
                this.nAME1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string VKBUR
        {
            get
            {
                return this.vKBURField;
            }
            set
            {
                this.vKBURField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string ARKTX
        {
            get
            {
                return this.aRKTXField;
            }
            set
            {
                this.aRKTXField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string VKGRP
        {
            get
            {
                return this.vKGRPField;
            }
            set
            {
                this.vKGRPField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string BEZEI
        {
            get
            {
                return this.bEZEIField;
            }
            set
            {
                this.bEZEIField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string BZIRK
        {
            get
            {
                return this.bZIRKField;
            }
            set
            {
                this.bZIRKField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string BZTXT
        {
            get
            {
                return this.bZTXTField;
            }
            set
            {
                this.bZTXTField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public string FKDAT
        {
            get
            {
                return this.fKDATField;
            }
            set
            {
                this.fKDATField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public string AUBEL
        {
            get
            {
                return this.aUBELField;
            }
            set
            {
                this.aUBELField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=12)]
        public string AUPOS
        {
            get
            {
                return this.aUPOSField;
            }
            set
            {
                this.aUPOSField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=13)]
        public string VGBEL
        {
            get
            {
                return this.vGBELField;
            }
            set
            {
                this.vGBELField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=14)]
        public string VGPOS
        {
            get
            {
                return this.vGPOSField;
            }
            set
            {
                this.vGPOSField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=15)]
        public string MATNR
        {
            get
            {
                return this.mATNRField;
            }
            set
            {
                this.mATNRField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=16)]
        public string MAKTX
        {
            get
            {
                return this.mAKTXField;
            }
            set
            {
                this.mAKTXField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=17)]
        public decimal FKIMG
        {
            get
            {
                return this.fKIMGField;
            }
            set
            {
                this.fKIMGField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=18)]
        public string VRKME
        {
            get
            {
                return this.vRKMEField;
            }
            set
            {
                this.vRKMEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=19)]
        public string MATKL
        {
            get
            {
                return this.mATKLField;
            }
            set
            {
                this.mATKLField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=20)]
        public string LGORT
        {
            get
            {
                return this.lGORTField;
            }
            set
            {
                this.lGORTField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=21)]
        public string LGOBE
        {
            get
            {
                return this.lGOBEField;
            }
            set
            {
                this.lGOBEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=22)]
        public string WERKS
        {
            get
            {
                return this.wERKSField;
            }
            set
            {
                this.wERKSField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=23)]
        public string WERKS_D
        {
            get
            {
                return this.wERKS_DField;
            }
            set
            {
                this.wERKS_DField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=24)]
        public decimal CMPRE
        {
            get
            {
                return this.cMPREField;
            }
            set
            {
                this.cMPREField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=25)]
        public decimal NETWR
        {
            get
            {
                return this.nETWRField;
            }
            set
            {
                this.nETWRField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=26)]
        public decimal MWSBP
        {
            get
            {
                return this.mWSBPField;
            }
            set
            {
                this.mWSBPField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=27)]
        public decimal KZWI6
        {
            get
            {
                return this.kZWI6Field;
            }
            set
            {
                this.kZWI6Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=28)]
        public decimal KZWI5
        {
            get
            {
                return this.kZWI5Field;
            }
            set
            {
                this.kZWI5Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=29)]
        public decimal XWORKG
        {
            get
            {
                return this.xWORKGField;
            }
            set
            {
                this.xWORKGField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=30)]
        public decimal XWORKF
        {
            get
            {
                return this.xWORKFField;
            }
            set
            {
                this.xWORKFField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=31)]
        public decimal XWORKE
        {
            get
            {
                return this.xWORKEField;
            }
            set
            {
                this.xWORKEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=32)]
        public string KMEIN
        {
            get
            {
                return this.kMEINField;
            }
            set
            {
                this.kMEINField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=33)]
        public string WAERS
        {
            get
            {
                return this.wAERSField;
            }
            set
            {
                this.wAERSField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class ZSD_AMAZ_ORDER_INV_DETAILSResponse
    {
        
        private ZSD_AMAZ_ORDER_INV[] e_DETAILSField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public ZSD_AMAZ_ORDER_INV[] E_DETAILS
        {
            get
            {
                return this.e_DETAILSField;
            }
            set
            {
                this.e_DETAILSField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ZSD_AMAZ_ORDER_INV_DETAILSRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:rfc:functions", Order=0)]
        public DetailsInvoice.ZSD_AMAZ_ORDER_INV_DETAILS ZSD_AMAZ_ORDER_INV_DETAILS;
        
        public ZSD_AMAZ_ORDER_INV_DETAILSRequest()
        {
        }
        
        public ZSD_AMAZ_ORDER_INV_DETAILSRequest(DetailsInvoice.ZSD_AMAZ_ORDER_INV_DETAILS ZSD_AMAZ_ORDER_INV_DETAILS)
        {
            this.ZSD_AMAZ_ORDER_INV_DETAILS = ZSD_AMAZ_ORDER_INV_DETAILS;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ZSD_AMAZ_ORDER_INV_DETAILSResponse1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ZSD_AMAZ_ORDER_INV_DETAILS.Response", Namespace="urn:sap-com:document:sap:rfc:functions", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("ZSD_AMAZ_ORDER_INV_DETAILS.Response")]
        public DetailsInvoice.ZSD_AMAZ_ORDER_INV_DETAILSResponse ZSD_AMAZ_ORDER_INV_DETAILSResponse;
        
        public ZSD_AMAZ_ORDER_INV_DETAILSResponse1()
        {
        }
        
        public ZSD_AMAZ_ORDER_INV_DETAILSResponse1(DetailsInvoice.ZSD_AMAZ_ORDER_INV_DETAILSResponse ZSD_AMAZ_ORDER_INV_DETAILSResponse)
        {
            this.ZSD_AMAZ_ORDER_INV_DETAILSResponse = ZSD_AMAZ_ORDER_INV_DETAILSResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public interface ZSD_AMAZ_ORDER_INV_DETAILS_SRVChannel : DetailsInvoice.ZSD_AMAZ_ORDER_INV_DETAILS_SRV, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public partial class ZSD_AMAZ_ORDER_INV_DETAILS_SRVClient : System.ServiceModel.ClientBase<DetailsInvoice.ZSD_AMAZ_ORDER_INV_DETAILS_SRV>, DetailsInvoice.ZSD_AMAZ_ORDER_INV_DETAILS_SRV
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public ZSD_AMAZ_ORDER_INV_DETAILS_SRVClient() : 
                base(ZSD_AMAZ_ORDER_INV_DETAILS_SRVClient.GetDefaultBinding(), ZSD_AMAZ_ORDER_INV_DETAILS_SRVClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.binding.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ZSD_AMAZ_ORDER_INV_DETAILS_SRVClient(EndpointConfiguration endpointConfiguration) : 
                base(ZSD_AMAZ_ORDER_INV_DETAILS_SRVClient.GetBindingForEndpoint(endpointConfiguration), ZSD_AMAZ_ORDER_INV_DETAILS_SRVClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ZSD_AMAZ_ORDER_INV_DETAILS_SRVClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(ZSD_AMAZ_ORDER_INV_DETAILS_SRVClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ZSD_AMAZ_ORDER_INV_DETAILS_SRVClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(ZSD_AMAZ_ORDER_INV_DETAILS_SRVClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ZSD_AMAZ_ORDER_INV_DETAILS_SRVClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DetailsInvoice.ZSD_AMAZ_ORDER_INV_DETAILSResponse1 DetailsInvoice.ZSD_AMAZ_ORDER_INV_DETAILS_SRV.ZSD_AMAZ_ORDER_INV_DETAILS(DetailsInvoice.ZSD_AMAZ_ORDER_INV_DETAILSRequest request)
        {
            return base.Channel.ZSD_AMAZ_ORDER_INV_DETAILS(request);
        }
        
        public DetailsInvoice.ZSD_AMAZ_ORDER_INV_DETAILSResponse ZSD_AMAZ_ORDER_INV_DETAILS(DetailsInvoice.ZSD_AMAZ_ORDER_INV_DETAILS ZSD_AMAZ_ORDER_INV_DETAILS1)
        {
            DetailsInvoice.ZSD_AMAZ_ORDER_INV_DETAILSRequest inValue = new DetailsInvoice.ZSD_AMAZ_ORDER_INV_DETAILSRequest();
            inValue.ZSD_AMAZ_ORDER_INV_DETAILS = ZSD_AMAZ_ORDER_INV_DETAILS1;
            DetailsInvoice.ZSD_AMAZ_ORDER_INV_DETAILSResponse1 retVal = ((DetailsInvoice.ZSD_AMAZ_ORDER_INV_DETAILS_SRV)(this)).ZSD_AMAZ_ORDER_INV_DETAILS(inValue);
            return retVal.ZSD_AMAZ_ORDER_INV_DETAILSResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DetailsInvoice.ZSD_AMAZ_ORDER_INV_DETAILSResponse1> DetailsInvoice.ZSD_AMAZ_ORDER_INV_DETAILS_SRV.ZSD_AMAZ_ORDER_INV_DETAILSAsync(DetailsInvoice.ZSD_AMAZ_ORDER_INV_DETAILSRequest request)
        {
            return base.Channel.ZSD_AMAZ_ORDER_INV_DETAILSAsync(request);
        }
        
        public System.Threading.Tasks.Task<DetailsInvoice.ZSD_AMAZ_ORDER_INV_DETAILSResponse1> ZSD_AMAZ_ORDER_INV_DETAILSAsync(DetailsInvoice.ZSD_AMAZ_ORDER_INV_DETAILS ZSD_AMAZ_ORDER_INV_DETAILS)
        {
            DetailsInvoice.ZSD_AMAZ_ORDER_INV_DETAILSRequest inValue = new DetailsInvoice.ZSD_AMAZ_ORDER_INV_DETAILSRequest();
            inValue.ZSD_AMAZ_ORDER_INV_DETAILS = ZSD_AMAZ_ORDER_INV_DETAILS;
            return ((DetailsInvoice.ZSD_AMAZ_ORDER_INV_DETAILS_SRV)(this)).ZSD_AMAZ_ORDER_INV_DETAILSAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.binding))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.binding))
            {
                return new System.ServiceModel.EndpointAddress("https://onesapbtpqa.it-cpi016-rt.cfapps.ap20.hana.ondemand.com/cxf/Amazon/InvoiceD" +
                        "etails");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return ZSD_AMAZ_ORDER_INV_DETAILS_SRVClient.GetBindingForEndpoint(EndpointConfiguration.binding);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return ZSD_AMAZ_ORDER_INV_DETAILS_SRVClient.GetEndpointAddress(EndpointConfiguration.binding);
        }
        
        public enum EndpointConfiguration
        {
            
            binding,
        }
    }
}
