//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CreateOrder
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:sap-com:document:sap:rfc:functions", ConfigurationName="CreateOrder.ZSD_AMAZON_SALEORD_CRT_SRV")]
    public interface ZSD_AMAZON_SALEORD_CRT_SRV
    {
        
        // CODEGEN: Generating message contract since the operation ZSD_AMAZON_SALEORD_CRT is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="urn:sap-com:document:sap:rfc:functions:ZSD_AMAZON_SALEORD_CRT_SRV:ZSD_AMAZON_SALE" +
            "ORD_CRTRequest", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        CreateOrder.ZSD_AMAZON_SALEORD_CRTResponse1 ZSD_AMAZON_SALEORD_CRT(CreateOrder.ZSD_AMAZON_SALEORD_CRTRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:sap-com:document:sap:rfc:functions:ZSD_AMAZON_SALEORD_CRT_SRV:ZSD_AMAZON_SALE" +
            "ORD_CRTRequest", ReplyAction="*")]
        System.Threading.Tasks.Task<CreateOrder.ZSD_AMAZON_SALEORD_CRTResponse1> ZSD_AMAZON_SALEORD_CRTAsync(CreateOrder.ZSD_AMAZON_SALEORD_CRTRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class ZSD_AMAZON_SALEORD_CRT
    {
        
        private string cONDGRP_1Field;
        
        private string cONDGRP_2Field;
        
        private string cONDGRP_3Field;
        
        private string cONDGRP_4Field;
        
        private string cUST_NUMField;
        
        private string cUST_REFField;
        
        private string dIVISIONField;
        
        private ZSTR_AMA_SO_ITEM[] iTEMField;
        
        private string rEQ_DELIVERY_DATEField;
        
        private string sALEPOINTField;
        
        private string sALE_ORGField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string CONDGRP_1
        {
            get
            {
                return this.cONDGRP_1Field;
            }
            set
            {
                this.cONDGRP_1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string CONDGRP_2
        {
            get
            {
                return this.cONDGRP_2Field;
            }
            set
            {
                this.cONDGRP_2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string CONDGRP_3
        {
            get
            {
                return this.cONDGRP_3Field;
            }
            set
            {
                this.cONDGRP_3Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string CONDGRP_4
        {
            get
            {
                return this.cONDGRP_4Field;
            }
            set
            {
                this.cONDGRP_4Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string CUST_NUM
        {
            get
            {
                return this.cUST_NUMField;
            }
            set
            {
                this.cUST_NUMField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string CUST_REF
        {
            get
            {
                return this.cUST_REFField;
            }
            set
            {
                this.cUST_REFField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string DIVISION
        {
            get
            {
                return this.dIVISIONField;
            }
            set
            {
                this.dIVISIONField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public ZSTR_AMA_SO_ITEM[] ITEM
        {
            get
            {
                return this.iTEMField;
            }
            set
            {
                this.iTEMField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string REQ_DELIVERY_DATE
        {
            get
            {
                return this.rEQ_DELIVERY_DATEField;
            }
            set
            {
                this.rEQ_DELIVERY_DATEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string SALEPOINT
        {
            get
            {
                return this.sALEPOINTField;
            }
            set
            {
                this.sALEPOINTField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public string SALE_ORG
        {
            get
            {
                return this.sALE_ORGField;
            }
            set
            {
                this.sALE_ORGField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class ZSTR_AMA_SO_ITEM
    {
        
        private string iTEMNUMField;
        
        private string mATNUMField;
        
        private decimal rEQQTYField;
        
        private string uOMField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string ITEMNUM
        {
            get
            {
                return this.iTEMNUMField;
            }
            set
            {
                this.iTEMNUMField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string MATNUM
        {
            get
            {
                return this.mATNUMField;
            }
            set
            {
                this.mATNUMField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public decimal REQQTY
        {
            get
            {
                return this.rEQQTYField;
            }
            set
            {
                this.rEQQTYField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string UOM
        {
            get
            {
                return this.uOMField;
            }
            set
            {
                this.uOMField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class ZSTR_AMAZON_RESPONSE
    {
        
        private string mSGField;
        
        private string mSGNRField;
        
        private string mSGTYPField;
        
        private string cATEGORYField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string MSG
        {
            get
            {
                return this.mSGField;
            }
            set
            {
                this.mSGField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string MSGNR
        {
            get
            {
                return this.mSGNRField;
            }
            set
            {
                this.mSGNRField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string MSGTYP
        {
            get
            {
                return this.mSGTYPField;
            }
            set
            {
                this.mSGTYPField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string CATEGORY
        {
            get
            {
                return this.cATEGORYField;
            }
            set
            {
                this.cATEGORYField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class ZSD_AMAZON_SALEORD_CRTResponse
    {
        
        private ZSTR_AMAZON_RESPONSE[] eT_RETURNField;
        
        private string sALE_ORDField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public ZSTR_AMAZON_RESPONSE[] ET_RETURN
        {
            get
            {
                return this.eT_RETURNField;
            }
            set
            {
                this.eT_RETURNField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string SALE_ORD
        {
            get
            {
                return this.sALE_ORDField;
            }
            set
            {
                this.sALE_ORDField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ZSD_AMAZON_SALEORD_CRTRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:rfc:functions", Order=0)]
        public CreateOrder.ZSD_AMAZON_SALEORD_CRT ZSD_AMAZON_SALEORD_CRT;
        
        public ZSD_AMAZON_SALEORD_CRTRequest()
        {
        }
        
        public ZSD_AMAZON_SALEORD_CRTRequest(CreateOrder.ZSD_AMAZON_SALEORD_CRT ZSD_AMAZON_SALEORD_CRT)
        {
            this.ZSD_AMAZON_SALEORD_CRT = ZSD_AMAZON_SALEORD_CRT;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ZSD_AMAZON_SALEORD_CRTResponse1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ZSD_AMAZON_SALEORD_CRT.Response", Namespace="urn:sap-com:document:sap:rfc:functions", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("ZSD_AMAZON_SALEORD_CRT.Response")]
        public CreateOrder.ZSD_AMAZON_SALEORD_CRTResponse ZSD_AMAZON_SALEORD_CRTResponse;
        
        public ZSD_AMAZON_SALEORD_CRTResponse1()
        {
        }
        
        public ZSD_AMAZON_SALEORD_CRTResponse1(CreateOrder.ZSD_AMAZON_SALEORD_CRTResponse ZSD_AMAZON_SALEORD_CRTResponse)
        {
            this.ZSD_AMAZON_SALEORD_CRTResponse = ZSD_AMAZON_SALEORD_CRTResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public interface ZSD_AMAZON_SALEORD_CRT_SRVChannel : CreateOrder.ZSD_AMAZON_SALEORD_CRT_SRV, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public partial class ZSD_AMAZON_SALEORD_CRT_SRVClient : System.ServiceModel.ClientBase<CreateOrder.ZSD_AMAZON_SALEORD_CRT_SRV>, CreateOrder.ZSD_AMAZON_SALEORD_CRT_SRV
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public ZSD_AMAZON_SALEORD_CRT_SRVClient() : 
                base(ZSD_AMAZON_SALEORD_CRT_SRVClient.GetDefaultBinding(), ZSD_AMAZON_SALEORD_CRT_SRVClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.binding.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ZSD_AMAZON_SALEORD_CRT_SRVClient(EndpointConfiguration endpointConfiguration) : 
                base(ZSD_AMAZON_SALEORD_CRT_SRVClient.GetBindingForEndpoint(endpointConfiguration), ZSD_AMAZON_SALEORD_CRT_SRVClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ZSD_AMAZON_SALEORD_CRT_SRVClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(ZSD_AMAZON_SALEORD_CRT_SRVClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ZSD_AMAZON_SALEORD_CRT_SRVClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(ZSD_AMAZON_SALEORD_CRT_SRVClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ZSD_AMAZON_SALEORD_CRT_SRVClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CreateOrder.ZSD_AMAZON_SALEORD_CRTResponse1 CreateOrder.ZSD_AMAZON_SALEORD_CRT_SRV.ZSD_AMAZON_SALEORD_CRT(CreateOrder.ZSD_AMAZON_SALEORD_CRTRequest request)
        {
            return base.Channel.ZSD_AMAZON_SALEORD_CRT(request);
        }
        
        public CreateOrder.ZSD_AMAZON_SALEORD_CRTResponse ZSD_AMAZON_SALEORD_CRT(CreateOrder.ZSD_AMAZON_SALEORD_CRT ZSD_AMAZON_SALEORD_CRT1)
        {
            CreateOrder.ZSD_AMAZON_SALEORD_CRTRequest inValue = new CreateOrder.ZSD_AMAZON_SALEORD_CRTRequest();
            inValue.ZSD_AMAZON_SALEORD_CRT = ZSD_AMAZON_SALEORD_CRT1;
            CreateOrder.ZSD_AMAZON_SALEORD_CRTResponse1 retVal = ((CreateOrder.ZSD_AMAZON_SALEORD_CRT_SRV)(this)).ZSD_AMAZON_SALEORD_CRT(inValue);
            return retVal.ZSD_AMAZON_SALEORD_CRTResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CreateOrder.ZSD_AMAZON_SALEORD_CRTResponse1> CreateOrder.ZSD_AMAZON_SALEORD_CRT_SRV.ZSD_AMAZON_SALEORD_CRTAsync(CreateOrder.ZSD_AMAZON_SALEORD_CRTRequest request)
        {
            return base.Channel.ZSD_AMAZON_SALEORD_CRTAsync(request);
        }
        
        public System.Threading.Tasks.Task<CreateOrder.ZSD_AMAZON_SALEORD_CRTResponse1> ZSD_AMAZON_SALEORD_CRTAsync(CreateOrder.ZSD_AMAZON_SALEORD_CRT ZSD_AMAZON_SALEORD_CRT)
        {
            CreateOrder.ZSD_AMAZON_SALEORD_CRTRequest inValue = new CreateOrder.ZSD_AMAZON_SALEORD_CRTRequest();
            inValue.ZSD_AMAZON_SALEORD_CRT = ZSD_AMAZON_SALEORD_CRT;
            return ((CreateOrder.ZSD_AMAZON_SALEORD_CRT_SRV)(this)).ZSD_AMAZON_SALEORD_CRTAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.binding))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.binding))
            {
                return new System.ServiceModel.EndpointAddress("https://onesapbtpqa.it-cpi016-rt.cfapps.ap20.hana.ondemand.com/cxf/Amazon/SaleOrdC" +
                        "rt");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return ZSD_AMAZON_SALEORD_CRT_SRVClient.GetBindingForEndpoint(EndpointConfiguration.binding);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return ZSD_AMAZON_SALEORD_CRT_SRVClient.GetEndpointAddress(EndpointConfiguration.binding);
        }
        
        public enum EndpointConfiguration
        {
            
            binding,
        }
    }
}
